# Server configurations
server:
  host: "DB_MYSQL_CLASSICREDITS00_CREDITSMLB_CREDITSMLB_ENDPOINT"
  regenerateSchema: false

WriteDBConfig:
  Url: creditsmlb_WPROD:${DB_MYSQL_CLASSICREDITS00_CREDITSMLB_CREDITSMLB_WPROD}@tcp(${DB_MYSQL_CLASSICREDITS00_CREDITSMLB_CREDITSMLB_ENDPOINT})/creditsmlb
